# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBwV-I8sGGGZ_m0KnPL9vgUdO9uPa8zW
"""

from telegram import Bot
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters

# Tokeningizni kiriting
TOKEN = 'YOUR-TELEGRAM-BOT-TOKEN'

def start(update, context):
    update.message.reply_text('Salom! Men sizning botimman!')

def help(update, context):
    update.message.reply_text('Bu bot yordamida xabar yuborishingiz mumkin.')

def main():
    updater = Updater(TOKEN, use_context=True)
    dispatcher = updater.dispatcher

    dispatcher.add_handler(CommandHandler("start", start))
    dispatcher.add_handler(CommandHandler("help", help))
    dispatcher.add_handler(MessageHandler(Filters.text & ~Filters.command, start))

    updater.start_polling()
    updater.idle()

if __name__ == '__main__':
    main()